# Generated by Django 5.0.4 on 2024-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='telefon',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
