# Generated by Django 5.0.4 on 2024-04-23 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_usuari_data_naixement_alter_usuari_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='usuari',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
