# Generated by Django 5.0.4 on 2024-05-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_prestec_estat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestec',
            name='data_préstec',
            field=models.DateTimeField(),
        ),
    ]
