# Generated by Django 5.0.4 on 2024-05-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_prestec_data_préstec'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestec',
            name='data_lliurament',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
