# Generated by Django 5.0.4 on 2024-04-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_article_ejemplares_alter_llibre_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
