# Generated by Django 5.0.4 on 2024-04-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_remove_article_disponibilidad_llibre_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llibre',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='article',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
